import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'jsr:@supabase/supabase-js@2';
// FABRICATION REMOVED 2026-09-19 — `detect_better_deals` invented offers and
// saved them to the database as real ones.
// ---------------------------------------------------------------------------
// If you are reading this with no other context: this action used to tell a
// traveller that a cheaper booking existed on another platform. No such
// booking was ever found, because no price-comparison provider is connected to
// this project and none was ever called. The entire offer was manufactured
// locally and then INSERTed into public.better_deals, where it became
// indistinguishable from a real deal to everything downstream.
//
// What was here, verbatim:
//
//   const basePrice = reservation?.total_price ? Number(reservation.total_price) : 150;
//   const allPlatforms = ['Booking.com', 'Expedia', 'Hotels.com', 'Airbnb'];
//   const count = Math.random() > 0.5 ? 2 : 1;
//   const shuffled = availablePlatforms.sort(() => Math.random() - 0.5).slice(0, count);
//   ...
//   const savings_pct = 10 + Math.random() * 15; // 10-25%
//   const savings = Math.round((basePrice * savings_pct) / 100 * 100) / 100;
//   const total_price = Math.round((basePrice - savings) * 100) / 100;
//   const free_cancellation = Math.random() > 0.5;
//   const url = 'https://travelos.app/deals/' + reservation_id;
//   await db.from('better_deals').insert({ ...  }) // persisted as a real deal
//
// Every part of that is invented:
//   * the competing platform is drawn from a hard-coded list, shuffled at
//     random — the named platform may not carry this property at all;
//   * the saving is Math.random() scaled to 10-25%, so the traveller was told
//     a specific dollar figure generated by a random number generator;
//   * when the reservation had no price, or did not exist, the base price fell
//     back to a literal 150, so the saving was a percentage of a made-up price;
//   * the currency fell back to 'USD' regardless of the booking;
//   * `free_cancellation` — a term with money attached — was a coin flip;
//   * the `url` was a stub route that resolves to nothing, so the traveller
//     could never reach the "deal" to check it;
//   * and the result was written to better_deals, so it persisted, was served
//     back on later calls as a stored deal, and outlived the request.
//
// WHAT IT DOES NOW
// There is no price-comparison provider in this project. The action performs no
// comparison, invents nothing, and WRITES NOTHING. It returns the project's
// ProviderResult envelope (`{ data: null, status: 'unavailable', ... }`, see
// PROMPT_5A2) with an explicit reason, so a caller cannot read an empty result
// as "we checked and you already have the best price" — which is itself a
// claim this project cannot support.
//
// Already-stored rows: better_deals was checked on 2026-09-19 and contained 0
// rows, so nothing fabricated is in it. That table had exactly one writer — the
// code deleted above — so ANY row found in better_deals predating this change
// is fabricated and must not be trusted. The lookup of existing rows is kept
// (it also backs `dismiss_deal`), but it now labels what it returns as stored
// rather than freshly verified.
//
// Whoever wires a real price provider: it belongs behind the 5A2
// ProviderAdapter, and a row may only be written to better_deals when a
// provider actually returned that offer, with the provider's own URL.
// ---------------------------------------------------------------------------
// COLUMN FIX 2026-09-19 — both booking_conflicts statements in this file named
// columns that do not exist on public.booking_conflicts. Its real columns are
// id, reservation_id, user_id, conflict_type, local_data, external_data,
// resolution, resolved_at, created_at. There is no `trip_id`, `severity`,
// `reservation_ids`, `suggestion`, `resolved` or `detected_at`.
//   * detect_conflicts INSERTed trip_id / severity / reservation_ids /
//     suggestion. PostgREST rejected every insert with 42703 and the error was
//     DISCARDED (`await db.from(...).insert(...)` with no destructuring), so
//     the conflicts were handed back to the caller and NOTHING was ever
//     persisted — the detection looked like it worked and the record vanished.
//   * get_conflicts filtered on `resolved` and ordered by `detected_at`, so it
//     failed with 42703 on every call and returned HTTP 500.
// The detail that has no column of its own now goes in `local_data`, which is
// the jsonb column this table provides for exactly that, and the trip is
// filtered through `local_data->>trip_id` so the endpoint keeps its contract.
const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS'
};
function jsonResponse(data, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: {
      ...CORS_HEADERS,
      'Content-Type': 'application/json'
    }
  });
}
function getServiceClient() {
  return createClient(Deno.env.get('SUPABASE_URL'), Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'));
}
async function getAuthUser(req) {
  const authHeader = req.headers.get('Authorization') ?? '';
  const token = authHeader.replace(/^Bearer\s+/i, '').trim();
  if (!token) return null;
  const supabase = createClient(Deno.env.get('SUPABASE_URL'), Deno.env.get('SUPABASE_ANON_KEY'));
  const { data, error } = await supabase.auth.getUser(token);
  if (error || !data.user) return null;
  return data.user;
}
// Action: record_snapshot
async function handleRecordSnapshot(userId, body) {
  const { reservation_id, provider, price, currency, room_rate, taxes, fees } = body;
  if (!reservation_id || !provider || price == null) {
    return jsonResponse({
      error: 'reservation_id, provider, price required'
    }, 400);
  }
  const db = getServiceClient();
  const { data, error } = await db.from('price_snapshots').insert({
    reservation_id,
    user_id: userId,
    provider,
    price,
    currency: currency ?? null,
    room_rate: room_rate ?? null,
    taxes: taxes ?? null,
    fees: fees ?? null
  }).select().single();
  if (error) return jsonResponse({
    error: error.message
  }, 500);
  return jsonResponse({
    success: true,
    snapshot: data
  });
}
// Action: get_price_history
async function handleGetPriceHistory(userId, body) {
  const reservation_id = body.reservation_id;
  if (!reservation_id) return jsonResponse({
    error: 'reservation_id required'
  }, 400);
  const db = getServiceClient();
  const { data, error } = await db.from('price_snapshots').select('price, recorded_at').eq('reservation_id', reservation_id).eq('user_id', userId).order('recorded_at', {
    ascending: true
  }).limit(30);
  if (error) return jsonResponse({
    error: error.message
  }, 500);
  return jsonResponse({
    price_history: data ?? []
  });
}
// Action: get_price_trend
async function handleGetPriceTrend(userId, body) {
  const reservation_id = body.reservation_id;
  if (!reservation_id) return jsonResponse({
    error: 'reservation_id required'
  }, 400);
  const db = getServiceClient();
  const { data, error } = await db.from('price_snapshots').select('price, recorded_at').eq('reservation_id', reservation_id).eq('user_id', userId).order('recorded_at', {
    ascending: false
  }).limit(30);
  if (error) return jsonResponse({
    error: error.message
  }, 500);
  const snapshots = (data ?? []).reverse();
  if (snapshots.length === 0) {
    return jsonResponse({
      trend: null
    });
  }
  const prices = snapshots.map((s)=>Number(s.price));
  const current_price = prices[prices.length - 1];
  const lowest_price = Math.min(...prices);
  const highest_price = Math.max(...prices);
  const average_price = prices.reduce((a, b)=>a + b, 0) / prices.length;
  const first_price = prices[0];
  const price_change_pct = first_price !== 0 ? (current_price - first_price) / first_price * 100 : 0;
  const trend = price_change_pct > 2 ? 'increasing' : price_change_pct < -2 ? 'decreasing' : 'stable';
  return jsonResponse({
    trend: {
      current_price,
      lowest_price,
      highest_price,
      average_price: Math.round(average_price * 100) / 100,
      price_change_pct: Math.round(price_change_pct * 100) / 100,
      trend,
      snapshot_count: snapshots.length
    }
  });
}
// Action: detect_better_deals
//
// FABRICATION REMOVED 2026-09-19 — see the block at the top of this file for
// the code that used to be here and exactly what it invented. Summary: the
// platform, the saving, the total price, the free-cancellation flag and the URL
// were all manufactured (Math.random(), a hard-coded platform list, a literal
// 150 base price) and then written to better_deals as real offers.
//
// No price-comparison provider exists in this project, so this action now
// compares nothing, invents nothing and writes nothing.
async function handleDetectBetterDeals(userId, body) {
  const reservation_id = body.reservation_id;
  if (!reservation_id) return jsonResponse({
    error: 'reservation_id required'
  }, 400);
  const db = getServiceClient();
  // Previously stored, non-expired, non-dismissed rows. Kept because
  // `dismiss_deal` acts on these ids and a UI that already showed one needs to
  // keep resolving it. NOTE: better_deals had exactly one writer before today
  // — the fabricator removed above — so any row returned here that predates
  // 2026-09-19 is fabricated. The table held 0 rows when this change was made.
  const { data: existing, error: existingErr } = await db.from('better_deals').select('id, platform, savings, savings_pct, total_price, currency, free_cancellation, url, detected_at').eq('reservation_id', reservation_id).eq('user_id', userId).eq('dismissed', false).gt('expires_at', new Date().toISOString());
  if (existingErr) {
    console.error('[price-tracker] better_deals lookup failed:', existingErr.message);
    return jsonResponse({
      error: 'better_deals_lookup_failed',
      details: existingErr.message
    }, 500);
  }
  if (existing && existing.length > 0) {
    return jsonResponse({
      deals: existing,
      data: {
        deals: existing
      },
      status: 'stale',
      source: 'stored: public.better_deals',
      // This function performed no comparison on this call. These rows were
      // written earlier and are not re-verified against any provider.
      live_comparison_performed: false,
      checked_at: new Date().toISOString()
    });
  }
  return jsonResponse({
    deals: [],
    data: null,
    status: 'unavailable',
    reason: 'no_price_comparison_provider_configured',
    safeFailureMessage: 'TravelOS cannot compare prices across booking platforms: no price-comparison provider is ' + 'connected. This does not mean a cheaper price does not exist — it means nothing was checked.',
    live_comparison_performed: false,
    persisted: false,
    checked_at: new Date().toISOString()
  });
}
// Action: dismiss_deal
async function handleDismissDeal(userId, body) {
  const deal_id = body.deal_id;
  if (!deal_id) return jsonResponse({
    error: 'deal_id required'
  }, 400);
  const db = getServiceClient();
  const { error } = await db.from('better_deals').update({
    dismissed: true
  }).eq('id', deal_id).eq('user_id', userId);
  if (error) return jsonResponse({
    error: error.message
  }, 500);
  return jsonResponse({
    success: true
  });
}
// Action: detect_conflicts
async function handleDetectConflicts(userId, body) {
  const trip_id = body.trip_id;
  const reservations = body.reservations;
  if (!trip_id || !Array.isArray(reservations)) {
    return jsonResponse({
      error: 'trip_id and reservations array required'
    }, 400);
  }
  const sorted = [
    ...reservations
  ].sort((a, b)=>new Date(a.check_in).getTime() - new Date(b.check_in).getTime());
  const conflicts = [];
  for(let i = 0; i < sorted.length - 1; i++){
    const curr = sorted[i];
    const next = sorted[i + 1];
    const currCheckOut = new Date(curr.check_out).getTime();
    const nextCheckIn = new Date(next.check_in).getTime();
    const gapMinutes = (nextCheckIn - currCheckOut) / 60000;
    if (currCheckOut > nextCheckIn) {
      conflicts.push({
        conflict_type: 'date-overlap',
        severity: 'critical',
        suggestion: `"${curr.name}" and "${next.name}" have overlapping dates. Consider adjusting check-out or check-in times.`,
        reservation_ids: [
          curr.id,
          next.id
        ]
      });
    } else if (gapMinutes < 120) {
      conflicts.push({
        conflict_type: 'time-gap',
        severity: 'warning',
        suggestion: `Only ${Math.round(gapMinutes)} minutes between "${curr.name}" check-out and "${next.name}" check-in. Allow more travel time.`,
        reservation_ids: [
          curr.id,
          next.id
        ]
      });
    }
  }
  const db = getServiceClient();
  const persisted = [];
  const failedToPersist = [];
  for (const conflict of conflicts){
    // COLUMN FIX 2026-09-19 — trip_id, severity, reservation_ids and suggestion
    // are not columns on booking_conflicts. reservation_id (singular) is, and
    // local_data is the jsonb column meant to carry the detail; the whole
    // conflict is recorded there so nothing is lost.
    const { error: insertErr } = await db.from('booking_conflicts').insert({
      user_id: userId,
      reservation_id: conflict.reservation_ids[0] ?? null,
      conflict_type: conflict.conflict_type,
      local_data: {
        trip_id,
        severity: conflict.severity,
        suggestion: conflict.suggestion,
        reservation_ids: conflict.reservation_ids
      }
    });
    if (insertErr) {
      console.error('[price-tracker] booking_conflicts insert failed:', insertErr.message);
      failedToPersist.push(conflict.conflict_type);
    } else {
      persisted.push(conflict.conflict_type);
    }
  }
  // Report persistence honestly rather than implying every detected conflict
  // was recorded.
  return jsonResponse({
    conflicts,
    persisted_count: persisted.length,
    failed_to_persist_count: failedToPersist.length
  });
}
// Action: get_conflicts
async function handleGetConflicts(userId, body) {
  const trip_id = body.trip_id;
  if (!trip_id) return jsonResponse({
    error: 'trip_id required'
  }, 400);
  const db = getServiceClient();
  // COLUMN FIX 2026-09-19 — was `.eq('trip_id', ...)`, `.eq('resolved', false)`
  // and `.order('detected_at')`; none of those three columns exists, so this
  // endpoint returned 500 on every call. The trip lives in local_data, the
  // resolved flag is the nullable `resolved_at` timestamp, and the timestamp
  // column is `created_at`.
  const { data, error } = await db.from('booking_conflicts').select('*').eq('user_id', userId).eq('local_data->>trip_id', trip_id).is('resolved_at', null).order('created_at', {
    ascending: false
  });
  if (error) return jsonResponse({
    error: error.message
  }, 500);
  return jsonResponse({
    conflicts: data ?? []
  });
}
Deno.serve(async (req)=>{
  if (req.method === 'OPTIONS') {
    return new Response(null, {
      status: 204,
      headers: CORS_HEADERS
    });
  }
  if (req.method !== 'POST') {
    return jsonResponse({
      error: 'Method not allowed'
    }, 405);
  }
  let body = {};
  try {
    body = await req.json();
  } catch (_e) {
    return jsonResponse({
      error: 'Invalid JSON body'
    }, 400);
  }
  const action = body.action;
  if (!action) return jsonResponse({
    error: 'action required'
  }, 400);
  const user = await getAuthUser(req);
  if (!user) return jsonResponse({
    error: 'unauthorized'
  }, 401);
  if (action === 'record_snapshot') return handleRecordSnapshot(user.id, body);
  if (action === 'get_price_history') return handleGetPriceHistory(user.id, body);
  if (action === 'get_price_trend') return handleGetPriceTrend(user.id, body);
  if (action === 'detect_better_deals') return handleDetectBetterDeals(user.id, body);
  if (action === 'dismiss_deal') return handleDismissDeal(user.id, body);
  if (action === 'detect_conflicts') return handleDetectConflicts(user.id, body);
  if (action === 'get_conflicts') return handleGetConflicts(user.id, body);
  return jsonResponse({
    error: 'Unknown action: ' + action
  }, 400);
});
